### ISSUE TITLE
Bit Vector not generated for a few APKs : trial run1 

### ISSUE THREAD

**Issue by amehrotra91** [twinklegupta/CS230-Project#13] opened 2017-05-28 23:34 UTC

**Comment by swati3124** [comment] 2017-06-01 19:48
The issue is with the parser. It is not able to detect or parse activities to write in AndroidManifest.xml file -> incorrect manifest file -> results in null opcode -> results in null feature vector

Incorrect manifest files attached for reference. Closing the issue.

[Archive.zip](https://github.com/twinklegupta/CS230-Project/files/1045861/Archive.zip)

**Closed by swati3124** 2017-06-01 19:48 UTC
